---
require:
  - rubocop-performance

AllCops:
  DisplayCopNames: true

Metrics/LineLength:
  Max: 150

Metrics/MethodLength:
  Max: 25

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'

Metrics/AbcSize:
  Enabled: No

Style/Documentation:
  Enabled: No

Style/DoubleNegation:
  Enabled: No

Naming/FileName:
  Enabled: No
