---
require:
  - rubocop-performance

AllCops:
  DisplayCopNames: true

Metrics/LineLength:
  Max: 150

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'

Style/Documentation:
  Enabled: No

Naming/FileName:
  Enabled: No
